# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'softwareArchitecture' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'ChameleonFramework'
  pod 'Bolts'
  pod 'PureLayout'

  # Pods for softwareArchitecture

  target 'softwareArchitectureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'softwareArchitectureUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
